node('maven') {
  stage('Build App') {
    git url: "https://github.com/siamaksade/cart-service.git"
    sh "mvn clean package -s src/main/config/settings.xml"
  }
  stage('Integration Test') {
    sh "mvn verify -s src/main/config/settings.xml"
  }
  stage('Build Image') {
    sh "oc start-build cart --from-file=target/cart.jar --follow"
  }
  stage('Deploy') {
    openshiftDeploy depCfg: 'cart'
    openshiftVerifyDeployment depCfg: 'cart', replicaCount: 1, verifyReplicaCount: true
  }
  stage('System Test') {
    sh "curl -s http://cart:8080/api/cart/FOO | grep 'cartItemTotal'"
  }
  stage('Approve') {
    timeout(time:15, unit:'MINUTES') {
      input message:'Approve Deploy to Prod?'
    }
  }
  stage('Promote') {
    openshiftTag srcStream: 'cart', srcTag: 'latest', namespace: 'dev', destStream: 'cart', destTag: 'prod', destinationNamespace: 'prod'
    openshiftVerifyDeployment depCfg: 'cart', replicaCount: 1, verifyReplicaCount: true, namespace: 'prod'
  }
}
