node('maven') {
  stage('Build App') {
    git url: "https://github.com/siamaksade/cart-service.git"
    sh "mvn clean package -s src/main/config/settings.xml"
  }
  stage('Integration Test') {
    sh "mvn verify -s src/main/config/settings.xml"
  }
  stage('Build Image') {
    sh "oc start-build cart --from-file=target/cart.jar --follow"
  }
  stage('Deploy') {
    openshiftDeploy(deploymentConfig: 'cart')
    openshiftVerifyDeployment(deploymentConfig: "cart", replicaCount: 1, verifyReplicaCount: true)
  }
  stage('System Test') {
    sh "curl -s http://cart:8080/api/cart/FOO | grep 'cartItemTotal'"
  }
}